---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app.okcoin.com/component: bihang-web
    app.okcoin.com/group: default
    app.okcoin.com/instance: bihang-web
    app.okcoin.com/manager-by: java
    app.okcoin.com/name: bihang-web
    app.okcoin.com/version: 2.0.0-SNAPSHOT
  name: bihang-web
  namespace: test
  annotations:
    fluxcd.io/automated: 'true'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.okcoin.com/name: bihang-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: 2019-04-17T11:03:54Z
        field.cattle.io/ports: '[[{"containerPort":8112,"dnsName":"bihang-web-","name":"8112tcp00","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp:
      labels:
        app.okcoin.com/name: bihang-web
    spec:
      containers:
      - env:
        - name: SPRING_CLOUD_CONFIG_PROFILE
          value: dev
        - name: SERVER_PORT
          value: "8112"
        - name: JAVA_OPTIONS
          value: -Xms1638m -Xmx1638m
        envFrom:
        - configMapRef:
            name: springcloud-consistency-conf
        image: harbor.okcoin-inc.com/okcoin/bihang-web:daily-0.0.3-07821a6
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 20
          httpGet:
            path: /
            port: 8112
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        name: main
        ports:
        - containerPort: 8112
          name: 8112tcp00
          protocol: TCP
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /
            port: 8112
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 2Gi
        securityContext:
          capabilities: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
