---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  annotations:
    fluxcd.io/locked_user: jian.ma <jian.ma@okcoin.net>
    fluxcd.io/locked: 'true'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16-alpine-perl
        ports:
        - containerPort: 80
