apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    field.cattle.io/creatorId: user-5spd8
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-okcoin-demo
  name: okcoin-demo
  namespace: test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-okcoin-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: 2019-07-15T02:34:01Z
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-okcoin-demo
    spec:
      containers:
      - image: harbor.okcoin-inc.com/okcoin/okcoin-demo:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: okcoin-demo
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
